### ISSUE TITLE
Unsafe legacy lifecycles warning

### ISSUE THREAD

**Issue by paschaldev** [mironov/react-redux-loading-bar#63]
I use the latest build of react and I get this warning in my console.

```
warning.js?6327:33 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

Connect(LoadingBar) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps
  componentWillUpdate

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by KevinJunJun** [comment]
+1

**Comment by mironov** [comment]
@paschaldev @KevinJunJun Please post your `yarn.lock` or `package-lock.json` files.

Loading Bar v4.0.3 does not contain legacy `componentWillReceiveProps` and `componentWillUpdate`.

I created a temporary repository with the latest React and Loading Bar: 
https://github.com/mironov/create-react-app-loading-bar
I don't see the warnings in the console.

**Comment by paschaldev** [comment]
I doubt. I cloned the repo of v4.0.3 and its still there.

```json 

//package-lock.json

"react-redux-loading-bar": {
      "version": "4.0.3",
      "resolved": "https://registry.npmjs.org/react-redux-loading-bar/-/react-redux-loading-bar-4.0.3.tgz",
      "integrity": "sha512-9pL6OzvdgEZU63kEMa1eEtt7EAefw83KRamVPF2h40yYgM2pt0RJX/VY58+tSkWhMpw21hlNF8P6RDWKv/UGpg==",
      "requires": {
        "prop-types": "^15.5.6",
        "react-lifecycles-compat": "^3.0.2"
      }
    },
```

**Comment by paschaldev** [comment]
Here is the console error again. Cleared my cache and built again 

```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

Connect(LoadingBar) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps
  componentWillUpdate

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
printWarning @ warning.js?6327:33
warning @ warning.js?6327:57
constructClassInstance @ react-dom.development.js?cada:6841
updateClassComponent @ react-dom.development.js?cada:8336
beginWork @ react-dom.development.js?cada:8982
performUnitOfWork @ react-dom.development.js?cada:11814
workLoop @ react-dom.development.js?cada:11843
renderRoot @ react-dom.development.js?cada:11874
performWorkOnRoot @ react-dom.development.js?cada:12449
performWork @ react-dom.development.js?cada:12370
performSyncWork @ react-dom.development.js?cada:12347
requestWork @ react-dom.development.js?cada:12247
scheduleWorkImpl @ react-dom.development.js?cada:12122
scheduleWork @ react-dom.development.js?cada:12082
scheduleRootUpdate @ react-dom.development.js?cada:12710
updateContainerAtExpirationTime @ react-dom.development.js?cada:12738
updateContainer @ react-dom.development.js?cada:12765
module.exports.webpackJsonp../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js?cada:16069
(anonymous) @ react-dom.development.js?cada:16488
unbatchedUpdates @ react-dom.development.js?cada:12557
legacyRenderSubtreeIntoContainer @ react-dom.development.js?cada:16484
hydrate @ react-dom.development.js?cada:16540
renderReactElement @ index.js?aef3:432
_callee4$ @ index.js?aef3:177
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:35
(anonymous) @ asyncToGenerator.js?7b11:14
doRender @ index.js?aef3:190
_callee2$ @ index.js?aef3:44
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:35
(anonymous) @ asyncToGenerator.js?7b11:14
render @ index.js?aef3:74
_callee$ @ index.js?aef3:415
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:35
(anonymous) @ asyncToGenerator.js?7b11:14
./node_modules/next/dist/client/next-dev.js @ next-dev.js?dd9a:31
__webpack_require__ @ [absolute-resource-path]:714
fn @ [absolute-resource-path]:117
0 @ core.css?bb0c:26
__webpack_require__ @ [absolute-resource-path]:714
webpackJsonpCallback @ [absolute-resource-path]:25
(anonymous) @ main.js:2
warning.js?6327:33 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

LoadingBar uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by mironov** [comment]
@paschaldev Spec description is incorrect. I'll update it.
What version of React do you use?

**Comment by paschaldev** [comment]
@mironov my react version 

"react": "^16.3.2",

**Comment by paschaldev** [comment]
I have no `react-lifecycles-compat` installed in my project. 

I didn't see the warning in that repository

**Comment by mironov** [comment]
@paschaldev I think I know what could be the culprit here.
Could you verify that you have `react-redux` at least v5.0.7 or later installed?

**Comment by paschaldev** [comment]
I have `redux` but not `react-redux. These are my dependencies 

```json

"dependencies": {
    "@zeit/next-sass": "0.1.1",
    "apollo-client-preset": "^1.0.8",
    "apollo-link-context": "^1.0.8",
    "autoprefixer": "^8.3.0",
    "cloudinary-react": "^1.0.6",
    "compression": "^1.7.2",
    "cookie-parser": "^1.4.3",
    "cross-fetch": "^2.1.1",
    "es6-promise": "^4.2.4",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.1",
    "history": "^4.7.2",
    "immutability-helper": "^2.6.6",
    "loadable-components": "^1.4.0",
    "lodash": "^4.17.10",
    "moment-mini": "^2.19.4",
    "next": "^5.1.0",
    "next-routes": "^1.4.1",
    "node-fetch": "^2.1.2",
    "password-maker": "^1.1.3",
    "postcss": "^6.0.14",
    "postcss-colour-functions": "^1.5.2",
    "postcss-conditionals": "^2.1.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-easy-import": "^3.0.0",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.1.4",
    "postcss-simple-vars": "^4.1.0",
    "prop-types": "^15.6.1",
    "react": "^16.3.2",
    "react-apollo": "^2.1.3",
    "react-dates": "^16.6.1",
    "react-datez": "github:paschaldev/react-datez#build",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.3.2",
    "react-fancy-button": "^1.0.5",
    "react-icons": "^2.2.7",
    "react-loading-bar": "0.0.7",
    "react-redux-loading-bar": "^4.0.3",
    "react-redux-snackbar": "^1.1.0",
    "react-toastify": "^4.0.0-rc.5",
    "react-validate-form": "^1.0.6",
    "react-validify": "^4.0.0",
    "redux": "^4.0.0",
    "redux-promise-middleware": "^5.1.1",
    "redux-thunk": "^2.2.0",
    "semantic-ui-css": "^2.3.1",
    "semantic-ui-react": "^0.79.1",
    "tailwindcss": "^0.5.2",
    "universal-cookie": "^2.1.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.46",
    "@babel/core": "^7.0.0-beta.46",
    "@babel/plugin-proposal-export-default-from": "^7.0.0-beta.46",
    "@babel/preset-env": "^7.0.0-beta.46",
    "@zeit/next-bundle-analyzer": "^0.1.1",
    "babel-cli": "^6.26.0",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.13",
    "babel-plugin-webpack-loaders": "^0.9.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "classnames": "^2.2.5",
    "emit-file-loader": "0.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "node-sass": "^4.9.0",
    "nodemon": "^1.17.2",
    "react-hot-loader": "^4.1.2",
    "react-icons-kit": "^1.0.7",
    "redux-devtools-extension": "^2.13.2",
    "redux-logger": "^3.0.6",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.3",
    "styled-jsx": "^2.2.6",
    "styled-jsx-css-loader": "^0.3.0",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack-bundle-analyzer": "^2.11.1"
  },
```

**Comment by mironov** [comment]
@paschaldev `react-redux` is a peer dependency for the Loading Bar. It is used to connect the component to the Redux store. Please install `react-redux` v5.0.7 and that should fix the issue.

**Comment by paschaldev** [comment]
@mironov I did install `react-redux` but I still get the warning. 

`"react-redux": "^5.0.7",`

**Comment by mironov** [comment]
@paschaldev Please post your full `package-lock.json`.

**Comment by paschaldev** [comment]
@mironov 

Here is the link 

https://gist.github.com/paschaldev/8d64c877fc832376b4e5d7d0c7c7858a

**Comment by KevinJunJun** [comment]
@paschaldev  I update the version of react-redux to 5.0.7 and solve the problem! Thx

**Comment by mironov** [comment]
@paschaldev Could it be that you're using `styled-components` or something similar that wraps the Loading Bar?
I ran out of ideas. I'll need an example repository to find out the root cause of the issue. It shouldn't happen with latest `react-redux-loading-bar` and `react-redux`.

**Comment by mironov** [comment]
@paschaldev I'm going to close the issue for now. The latest Loading Bar doesn't contain the legacy lifecycles. It must be something with your specific setup that couldn't be diagnosed without looking into the code. Feel free to reopen the issue if you have more info.

**Comment by paschaldev** [comment]
I'm sorry I didn't reply, Everything works fine now. Thanks

**Comment by sb-davidegironi** [comment]
Hello,
I've the same problem here.
@paschaldev  how did you solve?
I've try to yarn clean cache then yarn install, with no luck.

package dependecies here: https://pastebin.com/WqhpFgw3
    "react-redux": "^5.0.7",
    "react-redux-loading-bar": "^4.0.5",
yarn.lock here: https://pastebin.com/uHKCjT4U

Thanks!

**Comment by James-Dev** [comment]
Hi @paschaldev , could you let us know on how did you solve your issue?

Below are my package dependencies:
"react": "^16.4.1",
"react-redux": "^5.0.7",
"react-redux-loading-bar": "^4.0.5",

my full package.json can be found here: [https://pastebin.com/V7ngu1xL](https://pastebin.com/V7ngu1xL)
